modLoader = "javafml"
loaderVersion = "[39,)"
license = "AGPL v3"
[[mods]]
modId = "nextspring"
version = "1.0.1"
displayName = "NextSpring"
credits = ""
authors = "Tapio, Rinko1231"
description = "Though turned to mud, they'd quicken flowers' birth next spring."